---
- name: "Phase 2 : Network Configuration"
  hosts: just_parsed
  vars:
    ansible_ssh_user: administrator
    ansible_ssh_pass: C4mb14m1!
    ansible_become_pass: C4mb14m1!
    data: "{{ lookup('file', '../json/data.json') }}"
  gather_facts: false
  tasks:


    - debug:
        msg: GG
